/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.neo.box;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static int black=0x7f04000d;
        public static int black_least=0x7f040010;
        public static int black_mid=0x7f04000f;
        public static int black_most=0x7f04000e;
        public static int bottom_navigator_blue=0x7f040008;
        public static int color_444=0x7f040012;
        public static int color_555=0x7f040011;
        public static int color_60000=0x7f04001f;
        public static int color_70000=0x7f040020;
        public static int color_777=0x7f040018;
        public static int color_aaa=0x7f040015;
        public static int color_bbb=0x7f040016;
        public static int color_bg=0x7f040029;
        public static int color_blue_active=0x7f040028;
        public static int color_ccc=0x7f040021;
        public static int color_d8=0x7f04001b;
        public static int color_ddd=0x7f040017;
        public static int color_e0=0x7f04001e;
        public static int color_e5=0x7f040014;
        public static int color_eee=0x7f040013;
        public static int color_f0=0x7f04001d;
        public static int color_f7=0x7f040019;
        public static int color_f8=0x7f04001a;
        public static int color_fa=0x7f04001c;
        public static int color_fuyin_bg_normal=0x7f040003;
        public static int color_fuyin_bg_pressed=0x7f040002;
        public static int color_green=0x7f040023;
        public static int color_navigator_indicator_blue=0x7f040026;
        public static int color_red=0x7f040022;
        public static int color_tittle_bar=0x7f040024;
        public static int color_tittle_bar_lighter=0x7f040025;
        public static int color_txt_navigator_selected=0x7f040027;
        public static int color_white=0x7f040004;
        public static int color_yuanyin_bg_normal=0x7f040001;
        public static int color_yuanyin_bg_pressed=0x7f040000;
        public static int gray_least=0x7f04000b;
        public static int gray_mid=0x7f04000c;
        public static int half_black=0x7f04000a;
        public static int normal=0x7f040007;
        public static int pressed=0x7f040006;
        public static int stroke=0x7f040009;
        public static int transparent=0x7f040005;
    }
    public static final class dimen {
        public static int default_navigation_height=0x7f050001;
        public static int default_title_bar_height=0x7f050000;
    }
    public static final class drawable {
        public static int anim_list_but_bottom_navigator_01=0x7f020000;
        public static int anim_list_but_bottom_navigator_02=0x7f020001;
        public static int anim_list_but_bottom_navigator_03=0x7f020002;
        public static int anim_list_but_bottom_navigator_04=0x7f020003;
        public static int anim_list_but_bottom_navigator_05=0x7f020004;
        public static int anim_list_but_bottom_navigator_06=0x7f020005;
        public static int anim_list_but_bottom_navigator_07=0x7f020006;
        public static int anim_set_but_bottom_navigator_light_deep=0x7f020007;
        public static int ic_launcher=0x7f020008;
        public static int img_but_back=0x7f020009;
        public static int img_loading=0x7f02000a;
        public static int selector_bg_txt_check_class=0x7f02000b;
        public static int selector_but_back=0x7f02000c;
        public static int selector_but_bg=0x7f02000d;
        public static int selector_but_blue=0x7f02000e;
        public static int selector_but_login=0x7f02000f;
        public static int selector_but_logout=0x7f020010;
        public static int selector_but_note=0x7f020011;
        public static int selector_but_register=0x7f020012;
        public static int selector_default_tab_item_bg=0x7f020013;
        public static int selector_e5_ccc=0x7f020014;
        public static int selector_edit_exchange_comment=0x7f020015;
        public static int selector_edit_guess_key=0x7f020016;
        public static int selector_f0_e0=0x7f020017;
        public static int selector_fa_f0=0x7f020018;
        public static int selector_fff_f0=0x7f020019;
        public static int selector_top_search_bg=0x7f02001a;
        public static int selector_transparent_70000=0x7f02001b;
        public static int shape_bg_item=0x7f02001c;
        public static int style_progress_loading=0x7f02001d;
        public static int umeng_common_gradient_green=0x7f02001e;
        public static int umeng_common_gradient_orange=0x7f02001f;
        public static int umeng_common_gradient_red=0x7f020020;
        public static int umeng_update_button_cancel_bg_focused=0x7f020021;
        public static int umeng_update_button_cancel_bg_normal=0x7f020022;
        public static int umeng_update_button_cancel_bg_selector=0x7f020023;
        public static int umeng_update_button_cancel_bg_tap=0x7f020024;
        public static int umeng_update_button_ok_bg_focused=0x7f020025;
        public static int umeng_update_button_ok_bg_normal=0x7f020026;
        public static int umeng_update_button_ok_bg_selector=0x7f020027;
        public static int umeng_update_button_ok_bg_tap=0x7f020028;
        public static int umeng_update_dialog_bg=0x7f020029;
        public static int umeng_update_title_bg=0x7f02002a;
        public static int umeng_update_wifi_disable=0x7f02002b;
        public static int xlistview_arrow=0x7f02002c;
    }
    public static final class id {
        public static int bottom=0x7f080001;
        public static int but_title_bar_left=0x7f080005;
        public static int but_title_bar_right=0x7f080008;
        public static int but_view_tab_item=0x7f080003;
        public static int container_tab_item=0x7f080002;
        public static int progress_title_bar=0x7f080007;
        public static int top=0x7f080000;
        public static int txt_title_bar=0x7f080006;
        public static int txt_view_tab_item=0x7f080004;
        public static int xlistview_footer_content=0x7f080009;
        public static int xlistview_footer_hint_textview=0x7f08000b;
        public static int xlistview_footer_progressbar=0x7f08000a;
        public static int xlistview_header_arrow=0x7f080010;
        public static int xlistview_header_content=0x7f08000c;
        public static int xlistview_header_hint_textview=0x7f08000e;
        public static int xlistview_header_progressbar=0x7f080011;
        public static int xlistview_header_text=0x7f08000d;
        public static int xlistview_header_time=0x7f08000f;
    }
    public static final class layout {
        public static int test=0x7f030000;
        public static int view_tab_item=0x7f030001;
        public static int view_title_bar=0x7f030002;
        public static int xlistview_footer=0x7f030003;
        public static int xlistview_header=0x7f030004;
    }
    public static final class string {
        public static int app_name=0x7f060000;
        public static int xlistview_footer_hint_normal=0x7f060005;
        public static int xlistview_footer_hint_ready=0x7f060006;
        public static int xlistview_header_hint_loading=0x7f060003;
        public static int xlistview_header_hint_normal=0x7f060001;
        public static int xlistview_header_hint_ready=0x7f060002;
        public static int xlistview_header_last_time=0x7f060004;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static int AppBaseTheme=0x7f070000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static int AppTheme=0x7f070001;
    }
}
